name: Node.js CI/CD

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: create env file
      run: |
        touch .env
        echo APPLICATION_PORT=${{ secrets.APPLICATION_PORT }} >> .env  
        echo DATABASE_NAME=${{ secrets.DATABASE_NAME }} >> .env 
        echo DATABASE_USERNAME=${{ secrets.DATABASE_USERNAME }} >> .env 
        echo DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }} >> .env 
        echo JWT_SECRET=${{ secrets.JWT_SECRET }} >> .env 
        echo JWT_EXPIRES_IN=${{ secrets.JWT_EXPIRES_IN }} >> .env 
        echo SALT_ROUNDS=${{ secrets.SALT_ROUNDS }} >> .env
        echo OPENSEARCH_URL=${{ secrets.OPENSEARCH_URL }} >> .env
    - run: npm ci
    - run: pm2 restart back
